version: '3.9'

#Piyawat Loawthong 645162010022
#0022
#9922

services:
  sv_db:
    image: piyawatlot/dpu_ct519_lab_exam:img_mariadb
    container_name: ctn_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: piyawat.lo.passw0rd
      MARIADB_USER: piyawat.lo.user
      MARIADB_PASSWORD: piyawat.lo.passw0rd
      MARIADB_DATABASE: 0022_Lab_Exam
    volumes:
      - ./App_A/mariadb:/var/lib/mysql
    networks:
      app_net:
    ports:
      - "3306:3306"

  sv_dbadmin:
    image: piyawatlot/dpu_ct519_lab_exam:img_adminer
    container_name: ctn_adminer
    restart: always
    networks:
      app_net:
    ports:
      - "8081:8080"
    
  sv_webphp:
    image: piyawatlot/dpu_ct519_lab_exam:img_php
    container_name: ctn_php
    restart: always
    networks:
      app_net:
    volumes:
      - ./App_A/www/:/var/www/html
      - ./App_A/php/conf.d/:/usr/local/etc/php/conf.d
      - ./App_A/php/lib/:/usr/local/lib/php
    links:
      - "sv_db:database"
    ports:
      - "80:80"

  sv_webgo:
    image: piyawatlot/dpu_ct519_lab_exam:img_golang
    container_name: ctn_golang
    volumes:
      - ./App_B/go-with-compose/:/go/src/go-with-compose
      - ./App_B/go-with-compose/www/:/go/src/go-with-compose/www
    working_dir: /go/src/go-with-compose
    command: 'go run main.go'
    # command: 'sleep 7200'
    ports:
      - "9922:8080"
    expose:
      - "9922"

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
